// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjiyzgylsisylhccikct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqaXl6Z3lsc2lzeWxoY2Npa2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDYzMzgsImV4cCI6MjA3MjcyMjMzOH0.UoV0IJFJOdVLzVsz1jQmQ6BvOLPRGetkejfEIdr07V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});